<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="connectionsTest"
    errors="0" failures="1" hostname="" id="" package="funtionalTest" skipped="0"
    tests="1" time="75.00" timestamp="Fri, 15 Jul 2016 16:06:45 GMT">
  
    <testcase name="Add a new Internal Connection to a new Firm" time="75.00" assertions="21">

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

    

      <failure message="Testing if the URL contains &quot;#/addConnection&quot;.">    at Object.module.exports.Add a new Internal Connection to a new Firm (C:\Users\mzaman\Workspace\c9portaluitests\tests\funtionalTest\connectionsTest.js:28:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
  </testsuite>
</testsuites>
